SCREEN_ATT_L = 227;
SCREEN_ATT_W = 158;

SCREEN_LCD_L = 223;
SCREEN_LCD_W = 125;

CASE_WALL    = 10;

CASE_INNER_L = 280; // >= SCREEN_LCD_L + 50;
CASE_INNER_W = 180; // >= SCREEN_LCD_W + 50;

CASE_OUTER_L = CASE_INNER_L + CASE_WALL*2;
CASE_OUTER_W = CASE_INNER_W + CASE_WALL*2;

echo(CASE_INNER_L);
echo(CASE_INNER_W);

echo(CASE_OUTER_L);
echo(CASE_OUTER_W);
